Update patch set 1
Patch Set 1:

I may be doing something wrong, but my initial test with this after flashing via:
  ./flash-all-aosp.sh ../../Image.gz ../../sdm845-db845c.dtb 

Results in:

BootLinux: failed to get dtbo image
model does not exist in device tree
DTB offset is incorrect, kernel image does not have appended DTB
Error: Device Tree blob not found
Cmdline: firmware_class.path=/vendor/firmware/ androidboot.hardware=db845c init=/init androidboot.boot_devices=soc/1d84000.ufshc printk.devkmsg=on buildvariant=userded
Error finding #address-cells property
ERROR: Not a valid memory node found!
Invalid memory configuration, check memory partition table: Not Found
ERROR: Cannot update memory node
Device Tree update failed Status:Not Found
Launching fastboot

Trying to flash a Image.gz-dtb (along with the dtb file) also failed with the same error.

Amit: Anything I might be missing here?

Patch-set: 1
Reviewer: Gerrit User 1010110 <1010110@85c56323-6fa9-3386-8a01-6480fb634889>